#!/bin/sh

# The global variables
# =======================================================
endpoint="https://wttr.in/london"
current_date="$(date '+%d %b %Y')"
query=$(cat << EOF

What do you want the forecast to be shown?
1 |  Today's forecast
2 |  Three days of forecast that's started from now

[default=1]: 
EOF
)
help=$(cat << EOF

Usage: weather-forecast-cli <an argument>

1, -t, --today          Displaying today's forecast.
2, -a, --all            Displaying three days of forecast 
                        that's started from now.
-h, --help              Getting help for commands
EOF
)
# =======================================================


# the function to display the forecast that a user wants
display () {
  case "$1" in
    "1"|"-t"|"--today")
      sync_cache
      sed '1,1!d' /tmp/forecast.txt
      sed '8,17!d' /tmp/forecast.txt
      echo -e "\nFollow [46m[30m@igor_chubin[0m for wttr.in updates"
    ;;
    "2"|"-a"|"--all")
      sync_cache
      sed '1,1!d' /tmp/forecast.txt
      sed '8,37!d' /tmp/forecast.txt
      echo -e "\nFollow [46m[30m@igor_chubin[0m for wttr.in updates"
    ;;
    "help"|"h"|"-h"|"--help") echo "$help"
    ;;
    *) echo "Invalid argument. See the help below.$help"
    ;;
esac
}

sync_cache () {

  forecast_data_dir="$HOME/.local/share/weather-forecast-cli"
  forecast_file="$forecast_data_dir/forecast.txt"
  forecast_file_date="$(date -r $forecast_file '+%d %b %Y' 2> /dev/null)"

  if ! [ -f "$forecast_file" ] || [ "$forecast_file_date" != "$current_date" ] || [ $(cat $forecast_file) == "" ]; then
    mkdir -p "$forecast_data_dir"
    echo "Collecting the data..."
    curl "$endpoint" > "$forecast_file"
    cp $forecast_file /tmp

  elif ! [ -f "/tmp/forecast.txt" ]; then
    cp $forecast_file /tmp

  fi

}

# this is the first interface if the user doesn't give a single argument
if [ -z $1 ]; then
  read -p "$query " choose
  echo -e '\n'
  display "$choose"
else
  choose="$1"
  display "$choose"
fi
