#!/bin/bash

# The global variables
# =======================================================
endpoint="https://wttr.in/london"
quaesitum=$(cat << EOF

What do you want the forecast to be shown?
1 |  Today's forecast
2 |  Three days of forecast that's started from now

[default=1]: 
EOF
)
auxilium=$(cat << EOF

Usage: weather-forecast-cli <an argument>

1, -t, --today          Displaying today's forecast.
2, -a, --all            Displaying three days of forecast 
                        that's started from now.
-h, --help              Getting help for commands
EOF
)
# =======================================================


# the function to display the forecast that a user wants
ostentus () {
  case "$1" in
    "1"|"-t"|"--today")
      forecast="$(curl -s $endpoint)"
      echo -e "$forecast" | sed '1,1!d'
      echo -e "$forecast" | sed '8,17!d'
      echo -e "\nFollow [46m[30m@igor_chubin[0m for wttr.in updates"
    ;;
    "2"|"-a"|"--all")
      forecast="$(curl -s $endpoint)"
      echo -e "$forecast" | sed '1,1!d'
      echo -e "$forecast" | sed '8,37!d'
      echo -e "\nFollow [46m[30m@igor_chubin[0m for wttr.in updates"
    ;;
    *) echo "$auxilium"
    ;;
esac
}

# this is the first interface if the user doesn't give a single argument
if [ -z $1 ]; then
  read -p "$quaesitum " choose
  echo -e '\n'
  ostentus "$choose"
else
  choose="$1"
  ostentus "$choose"
fi
