#!/bin/sh

# The global variables
# =======================================================
endpoint="https://wttr.in/london"
current_date="$(date +'%d')"
quaesitum=$(cat << EOF

What do you want the forecast to be shown?
1 |  Today's forecast
2 |  Three days of forecast that's started from now

[default=1]: 
EOF
)
auxilium=$(cat << EOF

Usage: weather-forecast-cli <an argument>

1, -t, --today          Displaying today's forecast.
2, -a, --all            Displaying three days of forecast 
                        that's started from now.
-h, --help              Getting help for commands
EOF
)
# =======================================================


# the function to display the forecast that a user wants
ostentus () {
  case "$1" in
    "1"|"-t"|"--today")
      sync_cache
      forecast="$(cat /tmp/forecast.txt)"
      echo -e "$forecast" | sed '1,1!d'
      echo -e "$forecast" | sed '8,17!d'
      echo -e "\nFollow [46m[30m@igor_chubin[0m for wttr.in updates"
    ;;
    "2"|"-a"|"--all")
      sync_cache
      forecast="$(cat /tmp/forecast.txt)"
      echo -e "$forecast" | sed '1,1!d'
      echo -e "$forecast" | sed '8,37!d'
      echo -e "\nFollow [46m[30m@igor_chubin[0m for wttr.in updates"
    ;;
    *) echo "$auxilium"
    ;;
esac
}

sync_cache () {

  forecast_data_dir="$HOME/.local/share/weather-forecast-cli"
  forecast_file="$forecast_data_dir/forecast.txt"
  forecast_file_date="$(date -r $forecast_file +'%d' 2> /dev/null)"
  cache_date="$(date -r '/tmp/forecast.txt' +'%d' 2> /dev/null)"

  if ! [ -f "$forecast_file" ] || [ "$forecast_file_date" != "$current_date" ]; then
    mkdir -p "$forecast_data_dir"
    curl -s "$endpoint" > $forecast_file
    cp $forecast_file /tmp

  elif ! [ -f "/tmp/forecast.txt" ]; then
    cp $forecast_file /tmp

  fi

}

# this is the first interface if the user doesn't give a single argument
if [ -z $1 ]; then
  read -p "$quaesitum " choose
  echo -e '\n'
  ostentus "$choose"
else
  choose="$1"
  ostentus "$choose"
fi
